version: "3.7"

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:
  mypostgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Alex1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=kotikidb

  ownermicroservice:
    image: kotiki/ownermicroservice
    build: ./owner-microservice
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - mypostgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mypostgres:5432/kotikidb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Alex1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  catmicroservice:
      image: kotiki/catmicroservice
      build: ./cat-microservice
      ports:
        - "8082:8082"
      restart: always
      depends_on:
        - mypostgres
        - ownermicroservice
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://mypostgres:5432/kotikidb
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=Alex1234
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  generalapi:
    image: kotiki/generalapi
    build: ./general-api
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mypostgres
      - ownermicroservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mypostgres:5432/kotikidb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Alex1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update